### ISSUE TITLE
Sample notebooks

### ISSUE THREAD

**Issue by paravatha** [Azure/feast-azure#3] opened 2021-10-09 00:30 UTC
Hey all, Glad to see this initiative. 
Earlier this year, I tried Feast 0.9 on GCP/GKE : https://paravatha.medium.com/feast-setup-your-own-ml-feature-store-on-kubernetes-5b3193c2b62c 

Unfortunately, I don't have access to create Redis. 
So, If you have any sample notebooks for just the offline store part, I'd like to give it a try.

**Comment by paravatha** [comment] 2021-10-09 19:52
> @paravatha thanks for the feedback! So you have access to a MS SQL Store (e.g. SQL Server, Azure SQL DB, Synapse) but you cannot create an Azure Cache for Redis?
> 
> We can get some more samples added in.

Thanks @samuel100. I am planning to try this on Azure Sandbox playground on ACG, "Redis Cache" is not available there
https://help.acloud.guru/hc/en-us/articles/360001389296

**Comment by tarockey** [comment] 2021-10-13 22:43
Regarding the sample notebooks - when trying to test the deployment to ACI, the example model_service_env.yml references `feast-azure-provider==0.1.0` as a pip package, and the Image fails to build. I assume this example is pending a push for this package to be included in pip, correct?

**Comment by samuel100** [comment] 2021-10-14 17:58
@tarockey We have just release the package to PyPi.

**Comment by samuel100** [comment] 2021-11-17 14:25
This is now a duplicate of #31 since Cosmos DB is available in the Azure Sandbox.

**Closed by samuel100** 2021-11-17 14:25 UTC
Labels: documentation
